apiVersion: v1
entries:
  pfc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-11-19T12:01:47.4750515Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 8e99882c689dc1d0ad0bfe2560c163b552e7bcf0287491dad2cae6c0f0787a36
    home: pfc.zaakonline.nl
    icon: pfc.zaakonline.nl
    name: pfc
    urls:
    - pfc-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-19T12:01:47.4617017Z"
