apiVersion: v1
entries:
  pfc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-06-08T08:54:57.164087167Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: c066ae1f008c05e6fbeb8d6eec2362f2c8bb0fe9d03aa9f0d9ad60d864fff9ac
    home: pfc.zaakonline.nl
    icon: pfc.zaakonline.nl
    name: pfc
    urls:
    - pfc-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-08T08:54:57.152211367Z"
